# goal
WayPoint waypoint
---
# result
string final_state # successful (succeeded), canceled (preempted), timeout (aborted)
---
# feedback
string current_state  
## current_state
# "approaching" (minimising translational distance),
# "aligning" (minimising rotational distance),
# "targetBlocked" 
# "pathBlocked"
# "robotBlocked"
# "planningFailed" 
# "estopped"
# "isDoingOA"